trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      displayName: 'Run without sudo'
      inputs:
        script: |
          apt-get update
          apt-get install doxygen
    - task: CmdLine@2
      displayName: 'Run with sudo'
      condition: always()
      inputs:
        script: |
          sudo apt-get update
          sudo apt-get install doxygen
